export const SET_STATES = "SET_STATES";
export const SET_COUNTIES = "SET_COUNTIES";
export const SELECT_STATE = "SELECT_STATE";
export const LOADING_SATATES = "LOADING_SATATES";
export const LOADING_SATATES_COMPLETE = "LOADING_SATATES_COMPLETE";
export const LOADING_DETAILS = "LOADING_DETAILS";
export const LOADING_DETAILS_COMPLETE = "LOADING_DETAILS_COMPLETE";
